import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Navbar & General
    shop: 'Shop',
    references: 'References',
    contact: 'Contact',
    admin: 'Admin',
    customerLogin: 'Login',
    customerRegister: 'Register',
    myAccount: 'My Account',
    logout: 'Logout',
    adminLogin: 'Admin Login',
    allRightsReserved: 'All rights reserved.',
    footerSlogan: 'Your Partner in Quality Solutions.',
    heroTitle: 'Packwise: Innovative Solutions',
    heroSubtitle: 'Providing top-tier packing, food & beverage, and hygiene products tailored to your needs.',
    now: 'Now',
    
    // Security & Trust
    secureCheckout: 'Secure Checkout',
    sslEncrypted: 'SSL Encrypted',
    trustedBusiness: 'Trusted Business',
    dataProtected: 'Data Protected',
    privacyNoticeTitle: 'We value your privacy',
    privacyNoticeText: 'We use cookies and secure technologies to enhance your experience and protect your data.',
    acceptPrivacy: 'Accept & Continue',
    viewPrivacyPolicy: 'View Privacy Policy',
    customerRating: 'Customer Rating',
    basedOnReviews: 'Based on {count} reviews',
    happyCustomers: 'Happy Customers',
    trustedWorldwide: 'Trusted Worldwide',
    yearsExperience: 'Years Experience',
    industryExpertise: 'Industry Expertise',
    fastDelivery: 'Fast Delivery',
    averageDeliveryTime: 'Average Delivery',
    returnPolicy: 'Return Policy',
    days: 'Days',
    moneyBackGuarantee: 'Money Back Guarantee',
    securePayments: 'Secure Payments',
    sslProtected: 'SSL Protected',
    whyChoosePackwise: 'Why Choose Packwise?',
    processing: 'Processing...',
    passwordWeak: 'Weak',
    passwordFair: 'Fair',
    passwordGood: 'Good',
    passwordStrong: 'Strong',
    passwordRequirements: 'Password must be 8+ characters with uppercase, lowercase, number, and special character',
    
    // Stock Management
    stockManagement: 'Stock Management',
    serialNumber: 'Serial Number',
    currentStock: 'Current Stock',
    stockLevels: 'Stock Levels',
    value: 'Value',
    status: 'Status',
    inStock: 'In Stock',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    normalStock: 'Normal Stock',
    allStock: 'All Stock',
    editStock: 'Edit Stock',
    exportReport: 'Export Report',
    refresh: 'Refresh',
    sortByName: 'Sort by Name',
    sortByStock: 'Sort by Stock',
    sortByPrice: 'Sort by Price',
    sortByCategory: 'Sort by Category',
    
    // User Account
    accountOverview: 'Account Overview',
    welcomeUser: 'Welcome, {name}!',
    myOrders: 'My Orders',
    myCart: 'My Cart',
    viewCart: 'View Cart',
    noOrdersYet: 'You have no orders yet.',
    orderId: 'Order ID',
    orderDate: 'Date',
    orderTotal: 'Total',
    orderItems: 'Items',
    shippingAddress: 'Shipping Address',
    deliveryOption: 'Delivery Option',
    youHaveItemsInCart: 'You have {count} item(s) in your cart.',
    profileSettings: 'Profile Settings',
    taxNumber: 'Tax Number',
    saveSettings: 'Save Settings',
    settingsUpdatedSuccess: 'Your settings have been updated successfully!',
    
    // Login/Register Pages
    loginTitle: 'Customer Login',
    registerTitle: 'Create Account',
    emailAddress: 'Email Address',
    password: 'Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    confirmPasswordError: 'New passwords do not match.',
    passwordMinLengthError: 'Password must be at least 8 characters.',
    confirm: 'Confirm',
    confirmPassword: 'Confirm Password',
    companyNameOptional: 'Company Name (Optional)',
    loginButton: 'Login',
    registerButton: 'Register',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    loginHere: 'Login here',
    registerHere: 'Register here',
    passwordsDoNotMatch: 'Passwords do not match.',
    registrationSuccess: 'Registration successful! Please login.',
    loginSuccess: 'Login successful! Welcome, {name}.',
    loginFailed: 'Login failed. Please check your credentials.',
    emailInUse: 'This email is already registered.',
    fullName: 'Full Name',
    areYouAdmin: "Are you an administrator?",
    adminLoginHere: "Admin Login",
    
    // Shop Page
    ourProducts: 'Our Products',
    productsSubtitle: 'Quality solutions for packing, food & beverage, and hygiene.',
    searchProducts: 'Search products...',
    allCategories: 'All Categories',
    noProductsFound: 'No products found matching your criteria.',
    
    // Product Card & Detail
    viewDetails: 'View Details',
    addToCart: 'Add to Cart',
    currentlyUnavailable: 'Currently unavailable',
    outOfStock: 'Out of stock',
    backToProducts: 'Back to Products',
    dimensions: 'Dimensions',
    stock: 'Stock',
    stockAvailable: 'available',
    productNotFound: 'Product not found.',
    goBackToShop: 'Go back to shop',
    
    // Cart Page
    yourShoppingCart: 'Your Shopping Cart',
    cartIsEmpty: 'Your cart is empty.',
    continueShopping: 'Continue Shopping',
    each: 'each',
    total: 'Total',
    proceedToCheckout: 'Proceed to Checkout',
    loginToCheckout: 'Login to Checkout',
    
    // Checkout Steps
    shippingAndDelivery: 'Shipping & Delivery',
    payment: 'Payment',
    confirmation: 'Confirmation',
    checkout: 'Checkout',
    shippingInfo: 'Shipping Info',
    shippingInformation: 'Shipping Information',
    paymentInformation: 'Payment Information',
    orderConfirmation: 'Order Confirmation',
    deliveryOptions: 'Delivery Options',
    standardDelivery: 'Standard Delivery (1-2 business days)',
    expressDelivery: 'Express Delivery (Next business day)',
    cardNumber: 'Card Number',
    expiryDate: 'Expiry Date',
    cvv: 'CVV',
    cardholderName: 'Cardholder Name',
    orderSummary: 'Order Summary',
    subtotal: 'Subtotal',
    delivery: 'Delivery',
    deliveryCost: 'Delivery Cost',
    placeOrder: 'Place Order',
    orderConfirmed: 'Order Confirmed!',
    thankYouForOrder: 'Thank you for your order!',
    orderNumber: 'Order Number',
    
    // Admin
    adminDashboard: 'Admin Dashboard',
    packwiseManagement: 'Packwise Management',
    username: 'Username',
    dashboardOverview: 'Dashboard Overview',
    manageProducts: 'Manage Products',
    manageOrders: 'Manage Orders',
    manageUsers: 'Manage Users',
    siteContent: 'Site Content',
    settings: 'Settings',
    totalRevenue: 'Total Revenue',
    totalOrders: 'Total Orders',
    totalProducts: 'Total Products',
    totalUsers: 'Total Users',
    recentOrders: 'Recent Orders',
    lowStockAlert: 'Low Stock Alert',
    addNewProduct: 'Add New Product',
    editProduct: 'Edit Product',
    updateProduct: 'Update Product',
    addProduct: 'Add Product',
    productName: 'Product Name',
    price: 'Price',
    quantity: 'Quantity',
    productIsActive: 'Product is Active',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    active: 'Active',
    inactive: 'Inactive',
    actions: 'Actions',
    product: 'Product',
    customer: 'Customer',
    date: 'Date',
    user: 'User',
    email: 'Email',
    company: 'Company',
    orders: 'Orders',
    
    // Enhanced Admin Features
    editUser: 'Edit User',
    adminAccess: 'Admin Access',
    saveChanges: 'Save Changes',
    optional: 'Optional',
    leaveBlankToKeepCurrent: 'Leave blank to keep current password',
    removeAdminAccess: 'Remove Admin Access',
    grantAdminAccess: 'Grant Admin Access',
    deleteUser: 'Delete User',
    role: 'Role',
    localization: 'Localization',
    currentLanguage: 'Current Language',
    translationManagement: 'Translation Management',
    translationInstructions: 'Manage translations for different languages. Changes will be applied immediately.',
    heroSection: 'Hero Section',
    contactInformation: 'Contact Information',
    footerContent: 'Footer Content',
    footerText: 'Footer Text',
    systemSettings: 'System Settings',
    generalSettings: 'General Settings',
    securitySettings: 'Security Settings',
    orderSettings: 'Order Settings',
    systemInformation: 'System Information',
    siteName: 'Site Name',
    siteDescription: 'Site Description',
    currency: 'Currency',
    maintenanceMode: 'Maintenance Mode',
    maintenanceModeDesc: 'Temporarily disable the site for maintenance',
    allowRegistration: 'Allow Registration',
    allowRegistrationDesc: 'Allow new users to register accounts',
    emailNotifications: 'Email Notifications',
    emailNotificationsDesc: 'Send email notifications for orders and updates',
    minimumOrderValue: 'Minimum Order Value',
    maximumOrderValue: 'Maximum Order Value',
    version: 'Version',
    lastUpdate: 'Last Update',
    
    // Notifications
    productUnavailableStock: 'Product is unavailable or insufficient stock.',
    insufficientStockWarning: 'Only {availableQty} more of {productName} available.',
    addedToCart: '{productName} added to cart!',
    itemRemovedCart: 'Item removed from cart.',
    cartUpdated: 'Cart updated.',
    adminLoginSuccess: 'Admin login successful!',
    adminLoginInvalid: 'Invalid admin credentials.',
    adminLoggedOut: 'Admin logged out.',
    productAddedSuccess: 'Product added successfully!',
    productUpdatedSuccess: 'Product updated successfully!',
    productDeletedSuccess: 'Product deleted successfully!',
    userUpdatedSuccess: 'User updated successfully!',
    userDeletedSuccess: 'User deleted successfully!',
    orderPlacedSuccessfully: 'Order placed successfully!',
    referencesUpdatedSuccess: 'References updated successfully!',
    contactInfoUpdatedSuccess: 'Contact information updated successfully!',
    
    // Contact
    contactUs: 'Contact Us',
    getInTouch: 'Get in Touch',
    contactIntro: 'Have a question or need a quote? Fill out the form below or reach out to us directly.',
    sendMessage: 'Send Message',
    message: 'Message',
    thankYouMessage: 'Thank you, {name}! Your message has been received.',
    
    // References
    ourValuedPartners: 'Our Valued Partners',
    referencesIntro: 'Packwise is proud to partner with a diverse range of businesses, providing top-quality solutions and reliable service.',
    noReferences: 'No references to display currently.',
    
    // More translations
    address: 'Address',
    phone: 'Phone',
    city: 'City',
    postalCode: 'Postal Code',
    country: 'Country',
    description: 'Description',
    imageURL: 'Image URL',
    left: 'left',
    getQuote: 'Get Quote',
    
    // Form validation
    nameRequired: 'Name is required',
    emailRequired: 'Email is required',
    addressRequired: 'Address is required',
    cityRequired: 'City is required',
    postalCodeRequired: 'Postal code is required',
    countryRequired: 'Country is required',
    invalidCardNumber: 'Invalid card number',
    invalidExpiryDate: 'Invalid expiry date',
    invalidCVV: 'Invalid CVV',
    cardholderNameRequired: 'Cardholder name is required',
    
    // Additional
    next: 'Next',
    previous: 'Previous',
    backToCart: 'Back to Cart',
    orderHistory: 'Order History',
    startShopping: 'Start Shopping',
    recentOrders: 'Recent Orders',
    totalOrders: 'Total Orders',
    viewOrders: 'View Orders',
    viewMyOrders: 'View My Orders',
    paymentProcessed: 'Payment Processed',
    whatHappensNext: 'What happens next?',
    orderProcessingInfo: 'We will process your order within 24 hours',
    shippingNotificationInfo: 'You will receive shipping notifications via email',
    trackingNumberInfo: 'A tracking number will be provided once shipped',
    deliveryTimeInfo: 'Delivery will arrive within the selected timeframe',
    
    // Security
    tooManyAttempts: 'Too many login attempts. Please try again later.',
    invalidEmail: 'Please enter a valid email address.',
    invalidEmailFormat: 'Invalid email format',
    passwordTooShort: 'Password is too short',
    secureLoginSubtitle: 'Access your account securely',
    accountTemporarilyBlocked: 'Account temporarily blocked due to multiple failed attempts',
    enterPassword: 'Enter your password',
    protectedBySSL: 'Protected by SSL',
    yourDataIsSafe: 'Your data is safe',
    createSecureAccount: 'Create your secure account',
    enterFullName: 'Enter your full name',
    enterCompanyName: 'Enter company name (optional)',
    createStrongPassword: 'Create a strong password',
    confirmYourPassword: 'Confirm your password',
    agreeToTermsText: 'I agree to the',
    termsAndConditions: 'Terms and Conditions',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    mustAgreeToTerms: 'You must agree to the terms and conditions',
    creating: 'Creating',
    nameTooShort: 'Name must be at least 2 characters',
    registrationFailed: 'Registration failed. Please try again.',
    notAnAdmin: 'Not an administrator?',
    customerLoginHere: 'Customer Login',
    adminLoginTitle: 'Admin Login'
  },
  sk: {
    // Navbar & General
    shop: 'Obchod',
    references: 'Referencie',
    contact: 'Kontakt',
    admin: 'Admin',
    customerLogin: 'Prihlásenie',
    customerRegister: 'Registrácia',
    myAccount: 'Môj Účet',
    logout: 'Odhlásiť',
    adminLogin: 'Admin Prihlásenie',
    allRightsReserved: 'Všetky práva vyhradené.',
    footerSlogan: 'Váš Partner v Kvalitných Riešeniach.',
    heroTitle: 'Packwise: Inovatívne Riešenia',
    heroSubtitle: 'Poskytujeme špičkové produkty pre balenie, potraviny a nápoje, a hygienu prispôsobené vašim potrebám.',
    now: 'Teraz',
    
    // Security & Trust
    secureCheckout: 'Bezpečná Pokladňa',
    sslEncrypted: 'SSL Šifrované',
    trustedBusiness: 'Dôveryhodný Podnik',
    dataProtected: 'Chránené Údaje',
    privacyNoticeTitle: 'Vážime si vaše súkromie',
    privacyNoticeText: 'Používame cookies a bezpečné technológie na zlepšenie vašej skúsenosti a ochranu vašich údajov.',
    acceptPrivacy: 'Prijať a Pokračovať',
    viewPrivacyPolicy: 'Zobraziť Zásady Ochrany Súkromia',
    customerRating: 'Hodnotenie Zákazníkov',
    basedOnReviews: 'Na základe {count} recenzií',
    happyCustomers: 'Spokojní Zákazníci',
    trustedWorldwide: 'Dôveryhodní Celosvetovo',
    yearsExperience: 'Rokov Skúseností',
    industryExpertise: 'Odbornosť v Odvetví',
    fastDelivery: 'Rýchle Doručenie',
    averageDeliveryTime: 'Priemerné Doručenie',
    returnPolicy: 'Zásady Vrátenia',
    days: 'Dní',
    moneyBackGuarantee: 'Záruka Vrátenia Peňazí',
    securePayments: 'Bezpečné Platby',
    sslProtected: 'SSL Chránené',
    whyChoosePackwise: 'Prečo si Vybrať Packwise?',
    processing: 'Spracováva sa...',
    passwordWeak: 'Slabé',
    passwordFair: 'Priemerné',
    passwordGood: 'Dobré',
    passwordStrong: 'Silné',
    passwordRequirements: 'Heslo musí mať 8+ znakov s veľkým písmenom, malým písmenom, číslom a špeciálnym znakom',
    
    // Stock Management
    stockManagement: 'Správa Zásob',
    serialNumber: 'Sériové Číslo',
    currentStock: 'Aktuálne Zásoby',
    stockLevels: 'Úrovne Zásob',
    value: 'Hodnota',
    status: 'Stav',
    inStock: 'Na Sklade',
    lowStock: 'Nízke Zásoby',
    outOfStock: 'Nie je na Sklade',
    normalStock: 'Normálne Zásoby',
    allStock: 'Všetky Zásoby',
    editStock: 'Upraviť Zásoby',
    exportReport: 'Exportovať Správu',
    refresh: 'Obnoviť',
    sortByName: 'Zoradiť podľa Názvu',
    sortByStock: 'Zoradiť podľa Zásob',
    sortByPrice: 'Zoradiť podľa Ceny',
    sortByCategory: 'Zoradiť podľa Kategórie',
    
    // User Account
    accountOverview: 'Prehľad Účtu',
    welcomeUser: 'Vitajte, {name}!',
    myOrders: 'Moje Objednávky',
    myCart: 'Môj Košík',
    viewCart: 'Zobraziť Košík',
    noOrdersYet: 'Zatiaľ nemáte žiadne objednávky.',
    orderId: 'ID Objednávky',
    orderDate: 'Dátum',
    orderTotal: 'Celkom',
    orderItems: 'Položky',
    shippingAddress: 'Dodacia Adresa',
    deliveryOption: 'Možnosť Doručenia',
    youHaveItemsInCart: 'Máte {count} položku/položiek v košíku.',
    profileSettings: 'Nastavenia Profilu',
    taxNumber: 'Daňové Číslo',
    saveSettings: 'Uložiť Nastavenia',
    settingsUpdatedSuccess: 'Vaše nastavenia boli úspešne aktualizované!',
    
    // Login/Register Pages
    loginTitle: 'Prihlásenie Zákazníka',
    registerTitle: 'Vytvoriť Účet',
    emailAddress: 'E-mailová Adresa',
    password: 'Heslo',
    newPassword: 'Nové Heslo',
    confirmNewPassword: 'Potvrdiť Nové Heslo',
    confirmPasswordError: 'Nové heslá sa nezhodujú.',
    passwordMinLengthError: 'Heslo musí mať aspoň 8 znakov.',
    confirm: 'Potvrdiť',
    confirmPassword: 'Potvrdiť Heslo',
    companyNameOptional: 'Názov Spoločnosti (Voliteľné)',
    loginButton: 'Prihlásiť',
    registerButton: 'Registrovať',
    dontHaveAccount: "Nemáte účet?",
    alreadyHaveAccount: 'Už máte účet?',
    loginHere: 'Prihláste sa tu',
    registerHere: 'Registrujte sa tu',
    passwordsDoNotMatch: 'Heslá sa nezhodujú.',
    registrationSuccess: 'Registrácia úspešná! Prosím prihláste sa.',
    loginSuccess: 'Prihlásenie úspešné! Vitajte, {name}.',
    loginFailed: 'Prihlásenie zlyhalo. Skontrolujte svoje údaje.',
    emailInUse: 'Tento e-mail je už registrovaný.',
    fullName: 'Celé Meno',
    areYouAdmin: "Ste administrátor?",
    adminLoginHere: "Admin Prihlásenie",
    
    // Shop Page
    ourProducts: 'Naše Produkty',
    productsSubtitle: 'Kvalitné riešenia pre balenie, potraviny a nápoje, a hygienu.',
    searchProducts: 'Hľadať produkty...',
    allCategories: 'Všetky Kategórie',
    noProductsFound: 'Neboli nájdené žiadne produkty zodpovedajúce vašim kritériám.',
    
    // Product Card & Detail
    viewDetails: 'Zobraziť Detaily',
    addToCart: 'Pridať do Košíka',
    currentlyUnavailable: 'Momentálne nedostupné',
    outOfStock: 'Nie je na sklade',
    backToProducts: 'Späť na Produkty',
    dimensions: 'Rozmery',
    stock: 'Sklad',
    stockAvailable: 'dostupné',
    productNotFound: 'Produkt nenájdený.',
    goBackToShop: 'Vrátiť sa do obchodu',
    
    // Cart Page
    yourShoppingCart: 'Váš Nákupný Košík',
    cartIsEmpty: 'Váš košík je prázdny.',
    continueShopping: 'Pokračovať v Nákupe',
    each: 'každý',
    total: 'Celkom',
    proceedToCheckout: 'Pokračovať k Pokladni',
    loginToCheckout: 'Prihlásiť sa k Pokladni',
    
    // Checkout Steps
    shippingAndDelivery: 'Doprava a Doručenie',
    payment: 'Platba',
    confirmation: 'Potvrdenie',
    checkout: 'Pokladňa',
    shippingInfo: 'Info o Doprave',
    shippingInformation: 'Informácie o Doprave',
    paymentInformation: 'Informácie o Platbe',
    orderConfirmation: 'Potvrdenie Objednávky',
    deliveryOptions: 'Možnosti Doručenia',
    standardDelivery: 'Štandardné Doručenie (1-2 pracovné dni)',
    expressDelivery: 'Expresné Doručenie (Nasledujúci pracovný deň)',
    cardNumber: 'Číslo Karty',
    expiryDate: 'Dátum Expirácie',
    cvv: 'CVV',
    cardholderName: 'Meno Držiteľa Karty',
    orderSummary: 'Súhrn Objednávky',
    subtotal: 'Medzisúčet',
    delivery: 'Doručenie',
    deliveryCost: 'Náklady na Doručenie',
    placeOrder: 'Zadať Objednávku',
    orderConfirmed: 'Objednávka Potvrdená!',
    thankYouForOrder: 'Ďakujeme za vašu objednávku!',
    orderNumber: 'Číslo Objednávky',
    
    // Admin
    adminDashboard: 'Admin Dashboard',
    packwiseManagement: 'Packwise Správa',
    username: 'Používateľské Meno',
    dashboardOverview: 'Prehľad Dashboardu',
    manageProducts: 'Spravovať Produkty',
    manageOrders: 'Spravovať Objednávky',
    manageUsers: 'Spravovať Používateľov',
    siteContent: 'Obsah Stránky',
    settings: 'Nastavenia',
    totalRevenue: 'Celkové Príjmy',
    totalOrders: 'Celkové Objednávky',
    totalProducts: 'Celkové Produkty',
    totalUsers: 'Celkoví Používatelia',
    recentOrders: 'Nedávne Objednávky',
    lowStockAlert: 'Upozornenie na Nízky Sklad',
    addNewProduct: 'Pridať Nový Produkt',
    editProduct: 'Upraviť Produkt',
    updateProduct: 'Aktualizovať Produkt',
    addProduct: 'Pridať Produkt',
    productName: 'Názov Produktu',
    price: 'Cena',
    quantity: 'Množstvo',
    productIsActive: 'Produkt je Aktívny',
    cancel: 'Zrušiť',
    edit: 'Upraviť',
    delete: 'Vymazať',
    active: 'Aktívny',
    inactive: 'Neaktívny',
    actions: 'Akcie',
    product: 'Produkt',
    status: 'Stav',
    customer: 'Zákazník',
    date: 'Dátum',
    user: 'Používateľ',
    email: 'E-mail',
    company: 'Spoločnosť',
    orders: 'Objednávky',
    
    // Enhanced Admin Features
    editUser: 'Upraviť Používateľa',
    adminAccess: 'Admin Prístup',
    saveChanges: 'Uložiť Zmeny',
    optional: 'Voliteľné',
    leaveBlankToKeepCurrent: 'Nechajte prázdne pre zachovanie súčasného hesla',
    removeAdminAccess: 'Odobrať Admin Prístup',
    grantAdminAccess: 'Udeliť Admin Prístup',
    deleteUser: 'Vymazať Používateľa',
    role: 'Rola',
    localization: 'Lokalizácia',
    currentLanguage: 'Súčasný Jazyk',
    translationManagement: 'Správa Prekladov',
    translationInstructions: 'Spravujte preklady pre rôzne jazyky. Zmeny sa aplikujú okamžite.',
    heroSection: 'Hero Sekcia',
    contactInformation: 'Kontaktné Informácie',
    footerContent: 'Obsah Pätičky',
    footerText: 'Text Pätičky',
    systemSettings: 'Systémové Nastavenia',
    generalSettings: 'Všeobecné Nastavenia',
    securitySettings: 'Bezpečnostné Nastavenia',
    orderSettings: 'Nastavenia Objednávok',
    systemInformation: 'Systémové Informácie',
    siteName: 'Názov Stránky',
    siteDescription: 'Popis Stránky',
    currency: 'Mena',
    maintenanceMode: 'Režim Údržby',
    maintenanceModeDesc: 'Dočasne zakázať stránku kvôli údržbe',
    allowRegistration: 'Povoliť Registráciu',
    allowRegistrationDesc: 'Povoliť novým používateľom registrovať účty',
    emailNotifications: 'E-mailové Notifikácie',
    emailNotificationsDesc: 'Posielať e-mailové notifikácie pre objednávky a aktualizácie',
    minimumOrderValue: 'Minimálna Hodnota Objednávky',
    maximumOrderValue: 'Maximálna Hodnota Objednávky',
    version: 'Verzia',
    lastUpdate: 'Posledná Aktualizácia',
    
    // Notifications
    productUnavailableStock: 'Produkt nie je dostupný alebo nedostatočný sklad.',
    insufficientStockWarning: 'Iba {availableQty} viac z {productName} dostupné.',
    addedToCart: '{productName} pridané do košíka!',
    itemRemovedCart: 'Položka odstránená z košíka.',
    cartUpdated: 'Košík aktualizovaný.',
    adminLoginSuccess: 'Admin prihlásenie úspešné!',
    adminLoginInvalid: 'Neplatné admin údaje.',
    adminLoggedOut: 'Admin odhlásený.',
    productAddedSuccess: 'Produkt úspešne pridaný!',
    productUpdatedSuccess: 'Produkt úspešne aktualizovaný!',
    productDeletedSuccess: 'Produkt úspešne vymazaný!',
    userUpdatedSuccess: 'Používateľ úspešne aktualizovaný!',
    userDeletedSuccess: 'Používateľ úspešne vymazaný!',
    orderPlacedSuccessfully: 'Objednávka úspešne zadaná!',
    referencesUpdatedSuccess: 'Referencie úspešne aktualizované!',
    contactInfoUpdatedSuccess: 'Kontaktné informácie úspešne aktualizované!',
    
    // Contact
    contactUs: 'Kontaktujte Nás',
    getInTouch: 'Ozvite Sa Nám',
    contactIntro: 'Máte otázku alebo potrebujete cenový odhad? Vyplňte formulár nižšie alebo nás kontaktujte priamo.',
    sendMessage: 'Odoslať Správu',
    message: 'Správa',
    thankYouMessage: 'Ďakujeme, {name}! Vaša správa bola prijatá.',
    
    // References
    ourValuedPartners: 'Naši Vážení Partneri',
    referencesIntro: 'Packwise je hrdý na partnerstvo s rozmanitou škálou podnikov, poskytujúc špičkovú kvalitu riešení a spoľahlivé služby.',
    noReferences: 'Momentálne nie sú k dispozícii žiadne referencie.',
    
    // More translations
    address: 'Adresa',
    phone: 'Telefón',
    city: 'Mesto',
    postalCode: 'PSČ',
    country: 'Krajina',
    description: 'Popis',
    imageURL: 'URL Obrázka',
    left: 'zostáva',
    getQuote: 'Získať Cenový Odhad',
    
    // Form validation
    nameRequired: 'Meno je povinné',
    emailRequired: 'E-mail je povinný',
    addressRequired: 'Adresa je povinná',
    cityRequired: 'Mesto je povinné',
    postalCodeRequired: 'PSČ je povinné',
    countryRequired: 'Krajina je povinná',
    invalidCardNumber: 'Neplatné číslo karty',
    invalidExpiryDate: 'Neplatný dátum expirácie',
    invalidCVV: 'Neplatné CVV',
    cardholderNameRequired: 'Meno držiteľa karty je povinné',
    
    // Additional
    next: 'Ďalej',
    previous: 'Predchádzajúce',
    backToCart: 'Späť do Košíka',
    orderHistory: 'História Objednávok',
    startShopping: 'Začať Nakupovanie',
    recentOrders: 'Nedávne Objednávky',
    totalOrders: 'Celkové Objednávky',
    viewOrders: 'Zobraziť Objednávky',
    viewMyOrders: 'Zobraziť Moje Objednávky',
    paymentProcessed: 'Platba Spracovaná',
    whatHappensNext: 'Čo sa stane ďalej?',
    orderProcessingInfo: 'Vašu objednávku spracujeme do 24 hodín',
    shippingNotificationInfo: 'Dostanete notifikácie o doprave cez e-mail',
    trackingNumberInfo: 'Sledovacie číslo bude poskytnuté po odoslaní',
    deliveryTimeInfo: 'Doručenie príde v rámci vybraného časového rámca',
    
    // Security
    tooManyAttempts: 'Príliš veľa pokusov o prihlásenie. Skúste to znova neskôr.',
    invalidEmail: 'Prosím zadajte platnú e-mailovú adresu.',
    invalidEmailFormat: 'Neplatný formát e-mailu',
    passwordTooShort: 'Heslo je príliš krátke',
    secureLoginSubtitle: 'Prístup k vášmu účtu bezpečne',
    accountTemporarilyBlocked: 'Účet dočasne zablokovaný kvôli viacerým neúspešným pokusom',
    enterPassword: 'Zadajte vaše heslo',
    protectedBySSL: 'Chránené SSL',
    yourDataIsSafe: 'Vaše údaje sú v bezpečí',
    createSecureAccount: 'Vytvorte si bezpečný účet',
    enterFullName: 'Zadajte vaše celé meno',
    enterCompanyName: 'Zadajte názov spoločnosti (voliteľné)',
    createStrongPassword: 'Vytvorte silné heslo',
    confirmYourPassword: 'Potvrďte vaše heslo',
    agreeToTermsText: 'Súhlasím s',
    termsAndConditions: 'Obchodnými Podmienkami',
    and: 'a',
    privacyPolicy: 'Zásadami Ochrany Súkromia',
    mustAgreeToTerms: 'Musíte súhlasiť s obchodnými podmienkami',
    creating: 'Vytvára sa',
    nameTooShort: 'Meno musí mať aspoň 2 znaky',
    registrationFailed: 'Registrácia zlyhala. Skúste to znova.',
    notAnAdmin: 'Nie ste administrátor?',
    customerLoginHere: 'Prihlásenie Zákazníka',
    adminLoginTitle: 'Admin Prihlásenie'
  },
  hu: {
    // Navbar & General
    shop: 'Bolt',
    references: 'Referenciák',
    contact: 'Kapcsolat',
    admin: 'Admin',
    customerLogin: 'Bejelentkezés',
    customerRegister: 'Regisztráció',
    myAccount: 'Fiókom',
    logout: 'Kijelentkezés',
    adminLogin: 'Admin Bejelentkezés',
    allRightsReserved: 'Minden jog fenntartva.',
    footerSlogan: 'Az Ön Partnere Minőségi Megoldásokban.',
    heroTitle: 'Packwise: Innovatív Megoldások',
    heroSubtitle: 'Csúcsminőségű csomagolási, élelmiszeripari és higiéniai termékeket kínálunk az Ön igényeihez igazítva.',
    now: 'Most',
    
    // Security & Trust
    secureCheckout: 'Biztonságos Fizetés',
    sslEncrypted: 'SSL Titkosított',
    trustedBusiness: 'Megbízható Vállalkozás',
    dataProtected: 'Védett Adatok',
    privacyNoticeTitle: 'Értékeljük az Ön magánéletét',
    privacyNoticeText: 'Cookie-kat és biztonságos technológiákat használunk az élmény javítása és adatok védelme érdekében.',
    acceptPrivacy: 'Elfogadás és Folytatás',
    viewPrivacyPolicy: 'Adatvédelmi Irányelvek Megtekintése',
    customerRating: 'Ügyfél Értékelés',
    basedOnReviews: '{count} értékelés alapján',
    happyCustomers: 'Elégedett Ügyfelek',
    trustedWorldwide: 'Világszerte Megbízható',
    yearsExperience: 'Év Tapasztalat',
    industryExpertise: 'Iparági Szakértelem',
    fastDelivery: 'Gyors Szállítás',
    averageDeliveryTime: 'Átlagos Szállítás',
    returnPolicy: 'Visszatérítési Szabályzat',
    days: 'Nap',
    moneyBackGuarantee: 'Pénzvisszafizetési Garancia',
    securePayments: 'Biztonságos Fizetések',
    sslProtected: 'SSL Védett',
    whyChoosePackwise: 'Miért Válassza a Packwise-t?',
    processing: 'Feldolgozás...',
    passwordWeak: 'Gyenge',
    passwordFair: 'Közepes',
    passwordGood: 'Jó',
    passwordStrong: 'Erős',
    passwordRequirements: 'A jelszónak 8+ karakterből kell állnia nagy- és kisbetűvel, számmal és speciális karakterrel',
    
    // Stock Management
    stockManagement: 'Készletkezelés',
    serialNumber: 'Sorozatszám',
    currentStock: 'Jelenlegi Készlet',
    stockLevels: 'Készletszintek',
    value: 'Érték',
    status: 'Állapot',
    inStock: 'Raktáron',
    lowStock: 'Alacsony Készlet',
    outOfStock: 'Nincs Raktáron',
    normalStock: 'Normál Készlet',
    allStock: 'Minden Készlet',
    editStock: 'Készlet Szerkesztése',
    exportReport: 'Jelentés Exportálása',
    refresh: 'Frissítés',
    sortByName: 'Rendezés Név Szerint',
    sortByStock: 'Rendezés Készlet Szerint',
    sortByPrice: 'Rendezés Ár Szerint',
    sortByCategory: 'Rendezés Kategória Szerint',
    
    // User Account
    accountOverview: 'Fiók Áttekintés',
    welcomeUser: 'Üdvözöljük, {name}!',
    myOrders: 'Rendeléseim',
    myCart: 'Kosaram',
    viewCart: 'Kosár Megtekintése',
    noOrdersYet: 'Még nincsenek rendelései.',
    orderId: 'Rendelés Azonosító',
    orderDate: 'Dátum',
    orderTotal: 'Összesen',
    orderItems: 'Tételek',
    shippingAddress: 'Szállítási Cím',
    deliveryOption: 'Szállítási Lehetőség',
    youHaveItemsInCart: '{count} tétel van a kosarában.',
    profileSettings: 'Profil Beállítások',
    taxNumber: 'Adószám',
    saveSettings: 'Beállítások Mentése',
    settingsUpdatedSuccess: 'A beállítások sikeresen frissítve!',
    
    // Login/Register Pages
    loginTitle: 'Ügyfél Bejelentkezés',
    registerTitle: 'Fiók Létrehozása',
    emailAddress: 'E-mail Cím',
    password: 'Jelszó',
    newPassword: 'Új Jelszó',
    confirmNewPassword: 'Új Jelszó Megerősítése',
    confirmPasswordError: 'Az új jelszavak nem egyeznek.',
    passwordMinLengthError: 'A jelszónak legalább 8 karakterből kell állnia.',
    confirm: 'Megerősítés',
    confirmPassword: 'Jelszó Megerősítése',
    companyNameOptional: 'Cégnév (Opcionális)',
    loginButton: 'Bejelentkezés',
    registerButton: 'Regisztráció',
    dontHaveAccount: "Nincs fiókja?",
    alreadyHaveAccount: 'Már van fiókja?',
    loginHere: 'Jelentkezzen be itt',
    registerHere: 'Regisztráljon itt',
    passwordsDoNotMatch: 'A jelszavak nem egyeznek.',
    registrationSuccess: 'Sikeres regisztráció! Kérjük jelentkezzen be.',
    loginSuccess: 'Sikeres bejelentkezés! Üdvözöljük, {name}.',
    loginFailed: 'Bejelentkezés sikertelen. Ellenőrizze adatait.',
    emailInUse: 'Ez az e-mail cím már regisztrálva van.',
    fullName: 'Teljes Név',
    areYouAdmin: "Ön adminisztrátor?",
    adminLoginHere: "Admin Bejelentkezés",
    
    // Shop Page
    ourProducts: 'Termékeink',
    productsSubtitle: 'Minőségi megoldások csomagoláshoz, élelmiszerekhez és higiéniához.',
    searchProducts: 'Termékek keresése...',
    allCategories: 'Minden Kategória',
    noProductsFound: 'Nem találhatók termékek a megadott kritériumoknak megfelelően.',
    
    // Product Card & Detail
    viewDetails: 'Részletek Megtekintése',
    addToCart: 'Kosárba',
    currentlyUnavailable: 'Jelenleg nem elérhető',
    outOfStock: 'Nincs raktáron',
    backToProducts: 'Vissza a Termékekhez',
    dimensions: 'Méretek',
    stock: 'Raktár',
    stockAvailable: 'elérhető',
    productNotFound: 'Termék nem található.',
    goBackToShop: 'Vissza a boltba',
    
    // Cart Page
    yourShoppingCart: 'Az Ön Bevásárlókosara',
    cartIsEmpty: 'A kosara ü res.',
    continueShopping: 'Vásárlás Folytatása',
    each: 'darab',
    total: 'Összesen',
    proceedToCheckout: 'Tovább a Pénztárhoz',
    loginToCheckout: 'Bejelentkezés a Pénztárhoz',
    
    // Checkout Steps
    shippingAndDelivery: 'Szállítás és Kézbesítés',
    payment: 'Fizetés',
    confirmation: 'Megerősítés',
    checkout: 'Pénztár',
    shippingInfo: 'Szállítási Info',
    shippingInformation: 'Szállítási Információk',
    paymentInformation: 'Fizetési Információk',
    orderConfirmation: 'Rendelés Megerősítése',
    deliveryOptions: 'Szállítási Lehetőségek',
    standardDelivery: 'Normál Szállítás (1-2 munkanap)',
    expressDelivery: 'Expressz Szállítás (Következő munkanap)',
    cardNumber: 'Kártyaszám',
    expiryDate: 'Lejárati Dátum',
    cvv: 'CVV',
    cardholderName: 'Kártyatulajdonos Neve',
    orderSummary: 'Rendelés Összefoglaló',
    subtotal: 'Részösszeg',
    delivery: 'Szállítás',
    deliveryCost: 'Szállítási Költség',
    placeOrder: 'Rendelés Leadása',
    orderConfirmed: 'Rendelés Megerősítve!',
    thankYouForOrder: 'Köszönjük a rendelését!',
    orderNumber: 'Rendelésszám',
    
    // Admin
    adminDashboard: 'Admin Irányítópult',
    packwiseManagement: 'Packwise Kezelés',
    username: 'Felhasználónév',
    dashboardOverview: 'Irányítópult Áttekintés',
    manageProducts: 'Termékek Kezelése',
    manageOrders: 'Rendelések Kezelése',
    manageUsers: 'Felhasználók Kezelése',
    siteContent: 'Oldal Tartalom',
    settings: 'Beállítások',
    totalRevenue: 'Összes Bevétel',
    totalOrders: 'Összes Rendelés',
    totalProducts: 'Összes Termék',
    totalUsers: 'Összes Felhasználó',
    recentOrders: 'Legutóbbi Rendelések',
    lowStockAlert: 'Alacsony Készlet Figyelmeztetés',
    addNewProduct: 'Új Termék Hozzáadása',
    editProduct: 'Termék Szerkesztése',
    updateProduct: 'Termék Frissítése',
    addProduct: 'Termék Hozzáadása',
    productName: 'Termék Neve',
    price: 'Ár',
    quantity: 'Mennyiség',
    productIsActive: 'Termék Aktív',
    cancel: 'Mégse',
    edit: 'Szerkesztés',
    delete: 'Törlés',
    active: 'Aktív',
    inactive: 'Inaktív',
    actions: 'Műveletek',
    product: 'Termék',
    status: 'Állapot',
    customer: 'Ügyfél',
    date: 'Dátum',
    user: 'Felhasználó',
    email: 'E-mail',
    company: 'Cég',
    orders: 'Rendelések',
    
    // Enhanced Admin Features
    editUser: 'Felhasználó Szerkesztése',
    adminAccess: 'Admin Hozzáférés',
    saveChanges: 'Változtatások Mentése',
    optional: 'Opcionális',
    leaveBlankToKeepCurrent: 'Hagyja üresen a jelenlegi jelszó megtartásához',
    removeAdminAccess: 'Admin Hozzáférés Eltávolítása',
    grantAdminAccess: 'Admin Hozzáférés Megadása',
    deleteUser: 'Felhasználó Törlése',
    role: 'Szerep',
    localization: 'Lokalizáció',
    currentLanguage: 'Jelenlegi Nyelv',
    translationManagement: 'Fordítás Kezelés',
    translationInstructions: 'Különböző nyelvek fordításainak kezelése. A változtatások azonnal alkalmazásra kerülnek.',
    heroSection: 'Főoldal Szekció',
    contactInformation: 'Kapcsolattartási Információk',
    footerContent: 'Lábléc Tartalom',
    footerText: 'Lábléc Szöveg',
    systemSettings: 'Rendszer Beállítások',
    generalSettings: 'Általános Beállítások',
    securitySettings: 'Biztonsági Beállítások',
    orderSettings: 'Rendelési Beállítások',
    systemInformation: 'Rendszer Információk',
    siteName: 'Oldal Neve',
    siteDescription: 'Oldal Leírása',
    currency: 'Pénznem',
    maintenanceMode: 'Karbantartási Mód',
    maintenanceModeDesc: 'Az oldal ideiglenes letiltása karbantartás miatt',
    allowRegistration: 'Regisztráció Engedélyezése',
    allowRegistrationDesc: 'Új felhasználók regisztrációjának engedélyezése',
    emailNotifications: 'E-mail Értesítések',
    emailNotificationsDesc: 'E-mail értesítések küldése rendelésekről és frissítésekről',
    minimumOrderValue: 'Minimális Rendelési Érték',
    maximumOrderValue: 'Maximális Rendelési Érték',
    version: 'Verzió',
    lastUpdate: 'Utolsó Frissítés',
    
    // Notifications
    productUnavailableStock: 'A termék nem elérhető vagy nincs elegendő készlet.',
    insufficientStockWarning: 'Csak {availableQty} darab {productName} elérhető még.',
    addedToCart: '{productName} hozzáadva a kosárhoz!',
    itemRemovedCart: 'Tétel eltávolítva a kosárból.',
    cartUpdated: 'Kosár frissítve.',
    adminLoginSuccess: 'Admin bejelentkezés sikeres!',
    adminLoginInvalid: 'Érvénytelen admin adatok.',
    adminLoggedOut: 'Admin kijelentkezve.',
    productAddedSuccess: 'Termék sikeresen hozzáadva!',
    productUpdatedSuccess: 'Termék sikeresen frissítve!',
    productDeletedSuccess: 'Termék sikeresen törölve!',
    userUpdatedSuccess: 'Felhasználó sikeresen frissítve!',
    userDeletedSuccess: 'Felhasználó sikeresen törölve!',
    orderPlacedSuccessfully: 'Rendelés sikeresen leadva!',
    referencesUpdatedSuccess: 'Referenciák sikeresen frissítve!',
    contactInfoUpdatedSuccess: 'Kapcsolattartási információk sikeresen frissítve!',
    
    // Contact
    contactUs: 'Lépjen Velünk Kapcsolatba',
    getInTouch: 'Vegye Fel Velünk a Kapcsolatot',
    contactIntro: 'Van kérdése vagy árajánlatra van szüksége? Töltse ki az alábbi űrlapot vagy lépjen velünk kapcsolatba közvetlenül.',
    sendMessage: 'Üzenet Küldése',
    message: 'Üzenet',
    thankYouMessage: 'Köszönjük, {name}! Az üzenete megérkezett.',
    
    // References
    ourValuedPartners: 'Tisztelt Partnereink',
    referencesIntro: 'A Packwise büszke arra, hogy sokféle vállalkozással működik együtt, kiváló minőségű megoldásokat és megbízható szolgáltatást nyújtva.',
    noReferences: 'Jelenleg nincsenek megjeleníthető referenciák.',
    
    // More translations
    address: 'Cím',
    phone: 'Telefon',
    city: 'Város',
    postalCode: 'Irányítószám',
    country: 'Ország',
    description: 'Leírás',
    imageURL: 'Kép URL',
    left: 'maradt',
    getQuote: 'Árajánlat Kérése',
    
    // Form validation
    nameRequired: 'A név megadása kötelező',
    emailRequired: 'Az e-mail megadása kötelező',
    addressRequired: 'A cím megadása kötelező',
    cityRequired: 'A város megadása kötelező',
    postalCodeRequired: 'Az irányítószám megadása kötelező',
    countryRequired: 'Az ország megadása kötelező',
    invalidCardNumber: 'Érvénytelen kártyaszám',
    invalidExpiryDate: 'Érvénytelen lejárati dátum',
    invalidCVV: 'Érvénytelen CVV',
    cardholderNameRequired: 'A kártyatulajdonos nevének megadása kötelező',
    
    // Additional
    next: 'Következő',
    previous: 'Előző',
    backToCart: 'Vissza a Kosárhoz',
    orderHistory: 'Rendelési Előzmények',
    startShopping: 'Vásárlás Kezdése',
    recentOrders: 'Legutóbbi Rendelések',
    totalOrders: 'Összes Rendelés',
    viewOrders: 'Rendelések Megtekintése',
    viewMyOrders: 'Rendeléseim Megtekintése',
    paymentProcessed: 'Fizetés Feldolgozva',
    whatHappensNext: 'Mi történik ezután?',
    orderProcessingInfo: 'A rendelését 24 órán belül feldolgozzuk',
    shippingNotificationInfo: 'Szállítási értesítéseket fog kapni e-mailben',
    trackingNumberInfo: 'Követési számot adunk meg a szállítás után',
    deliveryTimeInfo: 'A szállítás a kiválasztott időkereten belül érkezik',
    
    // Security
    tooManyAttempts: 'Túl sok bejelentkezési kísérlet. Kérjük próbálja újra később.',
    invalidEmail: 'Kérjük adjon meg egy érvényes e-mail címet.',
    invalidEmailFormat: 'Érvénytelen e-mail formátum',
    passwordTooShort: 'A jelszó túl rövid',
    secureLoginSubtitle: 'Biztonságos hozzáférés a fiókjához',
    accountTemporarilyBlocked: 'A fiók ideiglenesen blokkolva több sikertelen kísérlet miatt',
    enterPassword: 'Adja meg a jelszavát',
    protectedBySSL: 'SSL által védett',
    yourDataIsSafe: 'Az adatai biztonságban vannak',
    createSecureAccount: 'Hozza létre biztonságos fiókját',
    enterFullName: 'Adja meg a teljes nevét',
    enterCompanyName: 'Adja meg a cégnevet (opcionális)',
    createStrongPassword: 'Hozzon létre erős jelszót',
    confirmYourPassword: 'Erősítse meg a jelszavát',
    agreeToTermsText: 'Elfogadom a',
    termsAndConditions: 'Felhasználási Feltételeket',
    and: 'és',
    privacyPolicy: 'Adatvédelmi Irányelveket',
    mustAgreeToTerms: 'El kell fogadnia a felhasználási feltételeket',
    creating: 'Létrehozás',
    nameTooShort: 'A névnek legalább 2 karakterből kell állnia',
    registrationFailed: 'A regisztráció sikertelen. Kérjük próbálja újra.',
    notAnAdmin: 'Nem adminisztrátor?',
    customerLoginHere: 'Ügyfél Bejelentkezés',
    adminLoginTitle: 'Admin Bejelentkezés'
  }
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('en');
  const [uiTranslations, setUiTranslations] = useState(translations);

  const t = (key, params = {}) => {
    let translationString = uiTranslations[currentLanguage]?.[key] || 
                           translations['en']?.[key] || 
                           key;
    
    if (typeof translationString === 'function') {
      return translationString(params);
    }
    
    // Replace parameters in the string
    Object.keys(params).forEach(paramKey => {
      const regex = new RegExp(`{${paramKey}}`, 'g');
      translationString = translationString.replace(regex, params[paramKey]);
    });
    
    return translationString;
  };

  const getLocalized = (fieldObject, lang = currentLanguage) => {
    if (typeof fieldObject === 'object' && fieldObject !== null) {
      return fieldObject[lang] || 
             fieldObject['en'] || 
             Object.values(fieldObject)[0] || 
             '';
    }
    return fieldObject || '';
  };

  return (
    <LanguageContext.Provider value={{
      currentLanguage,
      setCurrentLanguage,
      t,
      getLocalized,
      uiTranslations,
      setUiTranslations
    }}>
      {children}
    </LanguageContext.Provider>
  );
};